version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
      - "9901:9901"  
    volumes:
      - ./backend:/app
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
